name: learn
run-name: ${{ github.actor }} is learning faster
on:
  push:
    tags:
      - "release-*_*_*"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: code
      - uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "code/README.md"
          draft: true
          prerelease: true

