name: learn
run-name: ${{ github.actor }} is learning
on:
  push:
    tags:
      - "release-*_*_*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          draft: true
          prerelease: true

