name: learn
run-name: ${{ github.actor }} is learning
on:
  push:
    tags:
      - "release-*_*_*"

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: README.md
          draft: true
          prerelease: true

